"""Curated real-player cores for the 48 World Cup 2026 squads.

Each entry is ``(name, role, club, tier)``:

  role  one of GK, CB, FB, DM, CM, AM, W, ST  (fine position used for the
        lineup template and the position scoring factor)
  tier  one of elite, star, starter, squad     (drives the per-90 rate and the
        club-strength multiplier in the squad-quality prior)

These are the players who actually matter for the projected eleven, the scorer
model, and the Golden Boot race. ``build_squads.py`` completes each squad to the
frozen 26 with role-appropriate depth so every team fields a full bench, and
calibrates non-penalty xG and xA per 90 from (role, tier). The numbers are
curated estimates anchored to club level; ``ingest.py`` documents how to swap in
live FBref and Understat per-90 rates via soccerdata without touching the model.
"""

from __future__ import annotations

# Designated penalty taker per team (must be one of the curated names below).
PENALTY_TAKERS: dict[str, str] = {
    "Argentina": "Lionel Messi",
    "France": "Kylian Mbappe",
    "England": "Harry Kane",
    "Spain": "Mikel Oyarzabal",
    "Portugal": "Cristiano Ronaldo",
    "Brazil": "Vinicius Junior",
    "Netherlands": "Memphis Depay",
    "Belgium": "Kevin De Bruyne",
    "Germany": "Kai Havertz",
    "Norway": "Erling Haaland",
    "Egypt": "Mohamed Salah",
    "Poland": "Robert Lewandowski",
    "Croatia": "Luka Modric",
    "Uruguay": "Federico Valverde",
    "Colombia": "James Rodriguez",
    "Mexico": "Raul Jimenez",
    "United States": "Christian Pulisic",
    "Canada": "Jonathan David",
    "Morocco": "Achraf Hakimi",
    "Japan": "Takefusa Kubo",
    "South Korea": "Son Heung-min",
    "Senegal": "Sadio Mane",
    "Switzerland": "Granit Xhaka",
}

# Real curated cores. Attackers and creators are prioritised since they drive the
# scorer model. Depth is filled procedurally by build_squads.py.
REAL: dict[str, list[tuple[str, str, str, str]]] = {
    "Argentina": [
        ("Emiliano Martinez", "GK", "Aston Villa", "elite"),
        ("Cuti Romero", "CB", "Tottenham", "star"),
        ("Nicolas Otamendi", "CB", "Benfica", "starter"),
        ("Nahuel Molina", "FB", "Atletico Madrid", "starter"),
        ("Nicolas Tagliafico", "FB", "Lyon", "starter"),
        ("Rodrigo De Paul", "CM", "Atletico Madrid", "star"),
        ("Enzo Fernandez", "CM", "Chelsea", "star"),
        ("Alexis Mac Allister", "CM", "Liverpool", "star"),
        ("Lionel Messi", "AM", "Inter Miami", "elite"),
        ("Julian Alvarez", "ST", "Atletico Madrid", "elite"),
        ("Lautaro Martinez", "ST", "Inter", "elite"),
        ("Angel Di Maria", "W", "Benfica", "star"),
    ],
    "France": [
        ("Mike Maignan", "GK", "AC Milan", "elite"),
        ("William Saliba", "CB", "Arsenal", "star"),
        ("Dayot Upamecano", "CB", "Bayern Munich", "star"),
        ("Jules Kounde", "FB", "Barcelona", "star"),
        ("Theo Hernandez", "FB", "AC Milan", "star"),
        ("Aurelien Tchouameni", "DM", "Real Madrid", "star"),
        ("Eduardo Camavinga", "CM", "Real Madrid", "star"),
        ("Antoine Griezmann", "AM", "Atletico Madrid", "star"),
        ("Kylian Mbappe", "ST", "Real Madrid", "elite"),
        ("Ousmane Dembele", "W", "Paris Saint-Germain", "star"),
        ("Marcus Thuram", "ST", "Inter", "star"),
        ("Bradley Barcola", "W", "Paris Saint-Germain", "starter"),
    ],
    "England": [
        ("Jordan Pickford", "GK", "Everton", "starter"),
        ("John Stones", "CB", "Manchester City", "star"),
        ("Marc Guehi", "CB", "Crystal Palace", "starter"),
        ("Trent Alexander-Arnold", "FB", "Real Madrid", "star"),
        ("Kyle Walker", "FB", "Manchester City", "starter"),
        ("Declan Rice", "DM", "Arsenal", "star"),
        ("Jude Bellingham", "AM", "Real Madrid", "elite"),
        ("Cole Palmer", "AM", "Chelsea", "star"),
        ("Bukayo Saka", "W", "Arsenal", "star"),
        ("Harry Kane", "ST", "Bayern Munich", "elite"),
        ("Phil Foden", "W", "Manchester City", "star"),
        ("Anthony Gordon", "W", "Newcastle", "starter"),
    ],
    "Spain": [
        ("Unai Simon", "GK", "Athletic Bilbao", "starter"),
        ("Robin Le Normand", "CB", "Atletico Madrid", "starter"),
        ("Aymeric Laporte", "CB", "Al-Nassr", "starter"),
        ("Dani Carvajal", "FB", "Real Madrid", "star"),
        ("Marc Cucurella", "FB", "Chelsea", "starter"),
        ("Rodri", "DM", "Manchester City", "elite"),
        ("Pedri", "CM", "Barcelona", "star"),
        ("Fabian Ruiz", "CM", "Paris Saint-Germain", "starter"),
        ("Lamine Yamal", "W", "Barcelona", "elite"),
        ("Nico Williams", "W", "Athletic Bilbao", "star"),
        ("Mikel Oyarzabal", "ST", "Real Sociedad", "starter"),
        ("Alvaro Morata", "ST", "AC Milan", "starter"),
    ],
    "Portugal": [
        ("Diogo Costa", "GK", "Porto", "star"),
        ("Ruben Dias", "CB", "Manchester City", "star"),
        ("Goncalo Inacio", "CB", "Sporting", "starter"),
        ("Joao Cancelo", "FB", "Al-Hilal", "star"),
        ("Nuno Mendes", "FB", "Paris Saint-Germain", "star"),
        ("Vitinha", "CM", "Paris Saint-Germain", "star"),
        ("Bruno Fernandes", "AM", "Manchester United", "star"),
        ("Bernardo Silva", "AM", "Manchester City", "star"),
        ("Rafael Leao", "W", "AC Milan", "star"),
        ("Cristiano Ronaldo", "ST", "Al-Nassr", "star"),
        ("Goncalo Ramos", "ST", "Paris Saint-Germain", "starter"),
        ("Pedro Neto", "W", "Chelsea", "starter"),
    ],
    "Brazil": [
        ("Alisson", "GK", "Liverpool", "elite"),
        ("Marquinhos", "CB", "Paris Saint-Germain", "star"),
        ("Gabriel Magalhaes", "CB", "Arsenal", "star"),
        ("Danilo", "FB", "Juventus", "starter"),
        ("Wendell", "FB", "Porto", "squad"),
        ("Bruno Guimaraes", "DM", "Newcastle", "star"),
        ("Lucas Paqueta", "CM", "West Ham", "starter"),
        ("Rodrygo", "W", "Real Madrid", "star"),
        ("Vinicius Junior", "W", "Real Madrid", "elite"),
        ("Raphinha", "W", "Barcelona", "star"),
        ("Endrick", "ST", "Real Madrid", "starter"),
        ("Joao Pedro", "ST", "Chelsea", "starter"),
    ],
    "Netherlands": [
        ("Bart Verbruggen", "GK", "Brighton", "starter"),
        ("Virgil van Dijk", "CB", "Liverpool", "elite"),
        ("Matthijs de Ligt", "CB", "Manchester United", "star"),
        ("Denzel Dumfries", "FB", "Inter", "starter"),
        ("Nathan Ake", "FB", "Manchester City", "starter"),
        ("Frenkie de Jong", "CM", "Barcelona", "star"),
        ("Tijjani Reijnders", "CM", "Manchester City", "star"),
        ("Cody Gakpo", "W", "Liverpool", "star"),
        ("Xavi Simons", "AM", "RB Leipzig", "star"),
        ("Memphis Depay", "ST", "Corinthians", "starter"),
        ("Donyell Malen", "W", "Aston Villa", "starter"),
        ("Wout Weghorst", "ST", "Ajax", "squad"),
    ],
    "Belgium": [
        ("Koen Casteels", "GK", "Al-Qadsiah", "starter"),
        ("Wout Faes", "CB", "Leicester", "starter"),
        ("Zeno Debast", "CB", "Sporting", "starter"),
        ("Timothy Castagne", "FB", "Fulham", "starter"),
        ("Arthur Theate", "FB", "Eintracht Frankfurt", "starter"),
        ("Amadou Onana", "DM", "Aston Villa", "starter"),
        ("Youri Tielemans", "CM", "Aston Villa", "starter"),
        ("Kevin De Bruyne", "AM", "Napoli", "elite"),
        ("Jeremy Doku", "W", "Manchester City", "star"),
        ("Romelu Lukaku", "ST", "Napoli", "star"),
        ("Leandro Trossard", "W", "Arsenal", "starter"),
        ("Charles De Ketelaere", "AM", "Atalanta", "starter"),
    ],
    "Germany": [
        ("Marc-Andre ter Stegen", "GK", "Barcelona", "star"),
        ("Antonio Rudiger", "CB", "Real Madrid", "star"),
        ("Jonathan Tah", "CB", "Bayern Munich", "starter"),
        ("Joshua Kimmich", "FB", "Bayern Munich", "star"),
        ("David Raum", "FB", "RB Leipzig", "starter"),
        ("Robert Andrich", "DM", "Bayer Leverkusen", "starter"),
        ("Florian Wirtz", "AM", "Liverpool", "elite"),
        ("Jamal Musiala", "AM", "Bayern Munich", "elite"),
        ("Leroy Sane", "W", "Bayern Munich", "star"),
        ("Kai Havertz", "ST", "Arsenal", "star"),
        ("Niclas Fullkrug", "ST", "West Ham", "starter"),
        ("Serge Gnabry", "W", "Bayern Munich", "starter"),
    ],
    "Croatia": [
        ("Dominik Livakovic", "GK", "Fenerbahce", "starter"),
        ("Josko Gvardiol", "CB", "Manchester City", "star"),
        ("Josip Sutalo", "CB", "Ajax", "starter"),
        ("Josip Stanisic", "FB", "Bayer Leverkusen", "starter"),
        ("Borna Sosa", "FB", "Ajax", "squad"),
        ("Luka Modric", "CM", "Real Madrid", "star"),
        ("Mateo Kovacic", "CM", "Manchester City", "star"),
        ("Marcelo Brozovic", "DM", "Al-Nassr", "starter"),
        ("Andrej Kramaric", "AM", "Hoffenheim", "starter"),
        ("Ante Budimir", "ST", "Osasuna", "starter"),
        ("Ivan Perisic", "W", "Hajduk Split", "starter"),
        ("Luka Sucic", "AM", "Real Sociedad", "squad"),
    ],
    "Uruguay": [
        ("Sergio Rochet", "GK", "Internacional", "starter"),
        ("Ronald Araujo", "CB", "Barcelona", "star"),
        ("Jose Maria Gimenez", "CB", "Atletico Madrid", "star"),
        ("Nahitan Nandez", "FB", "Al-Qadsiah", "starter"),
        ("Mathias Olivera", "FB", "Napoli", "starter"),
        ("Federico Valverde", "CM", "Real Madrid", "elite"),
        ("Manuel Ugarte", "DM", "Manchester United", "starter"),
        ("Nicolas De La Cruz", "AM", "Flamengo", "starter"),
        ("Facundo Pellistri", "W", "Panathinaikos", "squad"),
        ("Darwin Nunez", "ST", "Al-Hilal", "star"),
        ("Federico Vinas", "ST", "Leon", "squad"),
        ("Maximiliano Araujo", "W", "Sporting", "squad"),
    ],
    "Colombia": [
        ("Camilo Vargas", "GK", "Atlas", "starter"),
        ("Davinson Sanchez", "CB", "Galatasaray", "starter"),
        ("Yerry Mina", "CB", "Cagliari", "starter"),
        ("Daniel Munoz", "FB", "Crystal Palace", "starter"),
        ("Johan Mojica", "FB", "Mallorca", "squad"),
        ("Richard Rios", "CM", "Benfica", "starter"),
        ("Jefferson Lerma", "DM", "Crystal Palace", "starter"),
        ("James Rodriguez", "AM", "Leon", "star"),
        ("Luis Diaz", "W", "Bayern Munich", "elite"),
        ("Jhon Cordoba", "ST", "Krasnodar", "starter"),
        ("Rafael Santos Borre", "ST", "Internacional", "squad"),
        ("Jhon Arias", "W", "Wolves", "starter"),
    ],
    "Morocco": [
        ("Yassine Bounou", "GK", "Al-Hilal", "star"),
        ("Achraf Hakimi", "FB", "Paris Saint-Germain", "elite"),
        ("Noussair Mazraoui", "FB", "Manchester United", "star"),
        ("Nayef Aguerd", "CB", "Real Sociedad", "starter"),
        ("Romain Saiss", "CB", "Al-Shabab", "starter"),
        ("Sofyan Amrabat", "DM", "Fenerbahce", "starter"),
        ("Azzedine Ounahi", "CM", "Panathinaikos", "starter"),
        ("Hakim Ziyech", "AM", "Al-Duhail", "starter"),
        ("Brahim Diaz", "AM", "Real Madrid", "star"),
        ("Youssef En-Nesyri", "ST", "Fenerbahce", "starter"),
        ("Sofiane Boufal", "W", "Al-Rayyan", "starter"),
        ("Eliesse Ben Seghir", "W", "Monaco", "starter"),
    ],
    "Japan": [
        ("Zion Suzuki", "GK", "Parma", "starter"),
        ("Ko Itakura", "CB", "Borussia Monchengladbach", "starter"),
        ("Takehiro Tomiyasu", "CB", "Arsenal", "starter"),
        ("Hiroki Ito", "FB", "Bayern Munich", "starter"),
        ("Junya Ito", "W", "Reims", "star"),
        ("Wataru Endo", "DM", "Liverpool", "starter"),
        ("Hidemasa Morita", "CM", "Sporting", "starter"),
        ("Takefusa Kubo", "AM", "Real Sociedad", "star"),
        ("Kaoru Mitoma", "W", "Brighton", "star"),
        ("Daizen Maeda", "ST", "Celtic", "starter"),
        ("Ayase Ueda", "ST", "Feyenoord", "starter"),
        ("Takumi Minamino", "AM", "Monaco", "starter"),
    ],
    "South Korea": [
        ("Kim Seung-gyu", "GK", "Al-Shabab", "starter"),
        ("Kim Min-jae", "CB", "Bayern Munich", "star"),
        ("Kim Young-gwon", "CB", "Ulsan", "starter"),
        ("Kim Jin-su", "FB", "Jeonbuk", "squad"),
        ("Lee Ki-je", "FB", "Suwon FC", "squad"),
        ("Hwang In-beom", "CM", "Feyenoord", "starter"),
        ("Lee Jae-sung", "CM", "Mainz", "starter"),
        ("Son Heung-min", "W", "Los Angeles FC", "elite"),
        ("Lee Kang-in", "AM", "Paris Saint-Germain", "star"),
        ("Hwang Hee-chan", "ST", "Wolves", "starter"),
        ("Oh Hyeon-gyu", "ST", "Genk", "squad"),
        ("Hwang Ui-jo", "ST", "Alaves", "squad"),
    ],
    "United States": [
        ("Matt Turner", "GK", "Lyon", "starter"),
        ("Chris Richards", "CB", "Crystal Palace", "starter"),
        ("Tim Ream", "CB", "Charlotte", "starter"),
        ("Sergino Dest", "FB", "PSV", "starter"),
        ("Antonee Robinson", "FB", "Fulham", "star"),
        ("Tyler Adams", "DM", "Bournemouth", "starter"),
        ("Weston McKennie", "CM", "Juventus", "starter"),
        ("Yunus Musah", "CM", "AC Milan", "starter"),
        ("Christian Pulisic", "W", "AC Milan", "star"),
        ("Gio Reyna", "AM", "Borussia Dortmund", "starter"),
        ("Folarin Balogun", "ST", "Monaco", "starter"),
        ("Ricardo Pepi", "ST", "PSV", "starter"),
    ],
    "Mexico": [
        ("Guillermo Ochoa", "GK", "AVS", "starter"),
        ("Cesar Montes", "CB", "Lokomotiv Moscow", "starter"),
        ("Johan Vasquez", "CB", "Genoa", "starter"),
        ("Jorge Sanchez", "FB", "Cruz Azul", "squad"),
        ("Jesus Gallardo", "FB", "Toluca", "starter"),
        ("Edson Alvarez", "DM", "West Ham", "star"),
        ("Luis Romo", "CM", "Cruz Azul", "starter"),
        ("Orbelin Pineda", "AM", "AEK Athens", "starter"),
        ("Hirving Lozano", "W", "San Diego FC", "star"),
        ("Santiago Gimenez", "ST", "AC Milan", "star"),
        ("Raul Jimenez", "ST", "Fulham", "starter"),
        ("Alexis Vega", "W", "Toluca", "starter"),
    ],
    "Canada": [
        ("Maxime Crepeau", "GK", "Portland Timbers", "starter"),
        ("Alphonso Davies", "FB", "Bayern Munich", "elite"),
        ("Moise Bombito", "CB", "Nice", "starter"),
        ("Derek Cornelius", "CB", "Marseille", "starter"),
        ("Alistair Johnston", "FB", "Celtic", "starter"),
        ("Stephen Eustaquio", "CM", "Porto", "starter"),
        ("Ismael Kone", "CM", "Marseille", "starter"),
        ("Jonathan David", "ST", "Juventus", "star"),
        ("Cyle Larin", "ST", "Mallorca", "starter"),
        ("Tajon Buchanan", "W", "Villarreal", "starter"),
        ("Jacob Shaffelburg", "W", "Nashville", "squad"),
        ("Jonathan Osorio", "AM", "Toronto", "squad"),
    ],
    "Senegal": [
        ("Edouard Mendy", "GK", "Al-Ahli", "star"),
        ("Kalidou Koulibaly", "CB", "Al-Hilal", "star"),
        ("Abdou Diallo", "CB", "Al-Arabi", "starter"),
        ("Ismail Jakobs", "FB", "Galatasaray", "starter"),
        ("Krepin Diatta", "FB", "Monaco", "starter"),
        ("Pape Matar Sarr", "CM", "Tottenham", "starter"),
        ("Idrissa Gueye", "DM", "Everton", "starter"),
        ("Pape Gueye", "CM", "Villarreal", "squad"),
        ("Ismaila Sarr", "W", "Crystal Palace", "star"),
        ("Sadio Mane", "W", "Al-Nassr", "star"),
        ("Nicolas Jackson", "ST", "Bayern Munich", "star"),
        ("Boulaye Dia", "ST", "Lazio", "starter"),
    ],
    "Switzerland": [
        ("Yann Sommer", "GK", "Inter", "star"),
        ("Manuel Akanji", "CB", "Manchester City", "star"),
        ("Nico Elvedi", "CB", "Borussia Monchengladbach", "starter"),
        ("Ricardo Rodriguez", "FB", "Real Betis", "starter"),
        ("Silvan Widmer", "FB", "Mainz", "squad"),
        ("Granit Xhaka", "DM", "Bayer Leverkusen", "star"),
        ("Remo Freuler", "CM", "Bologna", "starter"),
        ("Xherdan Shaqiri", "AM", "Basel", "starter"),
        ("Dan Ndoye", "W", "Bologna", "starter"),
        ("Breel Embolo", "ST", "Monaco", "starter"),
        ("Ruben Vargas", "W", "Sevilla", "starter"),
        ("Zeki Amdouni", "ST", "Benfica", "squad"),
    ],
    "Norway": [
        ("Orjan Nyland", "GK", "Sevilla", "starter"),
        ("Kristoffer Ajer", "CB", "Brentford", "starter"),
        ("Leo Ostigard", "CB", "Rennes", "starter"),
        ("Julian Ryerson", "FB", "Borussia Dortmund", "starter"),
        ("David Moller Wolfe", "FB", "AZ", "squad"),
        ("Sander Berge", "DM", "Fulham", "starter"),
        ("Martin Odegaard", "AM", "Arsenal", "elite"),
        ("Patrick Berg", "CM", "Bodo/Glimt", "squad"),
        ("Antonio Nusa", "W", "RB Leipzig", "starter"),
        ("Erling Haaland", "ST", "Manchester City", "elite"),
        ("Alexander Sorloth", "ST", "Atletico Madrid", "star"),
        ("Oscar Bobb", "W", "Manchester City", "starter"),
    ],
    "Egypt": [
        ("Mohamed El Shenawy", "GK", "Al Ahly", "starter"),
        ("Mohamed Abdelmonem", "CB", "Nice", "starter"),
        ("Mahmoud Hamdy", "CB", "Zamalek", "starter"),
        ("Ahmed Hegazy", "CB", "Al-Ittihad", "squad"),
        ("Mohamed Hany", "FB", "Al Ahly", "squad"),
        ("Mohamed Elneny", "DM", "Al-Jazira", "starter"),
        ("Mahmoud Trezeguet", "W", "Trabzonspor", "starter"),
        ("Mohamed Salah", "W", "Liverpool", "elite"),
        ("Omar Marmoush", "ST", "Manchester City", "star"),
        ("Mostafa Mohamed", "ST", "Nantes", "starter"),
        ("Emam Ashour", "AM", "Al Ahly", "starter"),
        ("Ibrahim Adel", "AM", "Pyramids", "squad"),
    ],
    "Austria": [
        ("Patrick Pentz", "GK", "Brondby", "starter"),
        ("Kevin Danso", "CB", "Tottenham", "starter"),
        ("Maximilian Wober", "CB", "Borussia Monchengladbach", "starter"),
        ("Philipp Mwene", "FB", "Mainz", "squad"),
        ("Stefan Posch", "FB", "Bologna", "starter"),
        ("Nicolas Seiwald", "DM", "RB Leipzig", "starter"),
        ("Konrad Laimer", "CM", "Bayern Munich", "starter"),
        ("Christoph Baumgartner", "AM", "RB Leipzig", "star"),
        ("Marcel Sabitzer", "AM", "Borussia Dortmund", "star"),
        ("Marko Arnautovic", "ST", "Inter", "starter"),
        ("Michael Gregoritsch", "ST", "Freiburg", "starter"),
        ("Patrick Wimmer", "W", "Wolfsburg", "squad"),
    ],
    "Ecuador": [
        ("Hernan Galindez", "GK", "Huracan", "starter"),
        ("Piero Hincapie", "CB", "Bayer Leverkusen", "star"),
        ("Willian Pacho", "CB", "Paris Saint-Germain", "star"),
        ("Pervis Estupinan", "FB", "AC Milan", "starter"),
        ("Angelo Preciado", "FB", "Sporting", "starter"),
        ("Moises Caicedo", "DM", "Chelsea", "star"),
        ("Alan Franco", "CM", "Cruz Azul", "starter"),
        ("Kendry Paez", "AM", "Chelsea", "starter"),
        ("Kevin Rodriguez", "ST", "Union Saint-Gilloise", "squad"),
        ("Enner Valencia", "ST", "Internacional", "starter"),
        ("Gonzalo Plata", "W", "Flamengo", "starter"),
        ("Jeremy Sarmiento", "W", "Brighton", "squad"),
    ],
    "Australia": [
        ("Mat Ryan", "GK", "Roma", "starter"),
        ("Harry Souttar", "CB", "Sheffield United", "starter"),
        ("Kye Rowles", "CB", "Hearts", "starter"),
        ("Aziz Behich", "FB", "Melbourne City", "starter"),
        ("Nathaniel Atkinson", "FB", "Hearts", "squad"),
        ("Aiden O'Neill", "DM", "Standard Liege", "starter"),
        ("Jackson Irvine", "CM", "St. Pauli", "starter"),
        ("Riley McGree", "AM", "Middlesbrough", "starter"),
        ("Martin Boyle", "W", "Hibernian", "starter"),
        ("Mitchell Duke", "ST", "Machida Zelvia", "starter"),
        ("Kusini Yengi", "ST", "Portsmouth", "squad"),
        ("Craig Goodwin", "W", "Al-Wehda", "starter"),
    ],
    "Turkey": [
        ("Mert Gunok", "GK", "Besiktas", "starter"),
        ("Merih Demiral", "CB", "Al-Ahli", "starter"),
        ("Abdulkerim Bardakci", "CB", "Galatasaray", "starter"),
        ("Zeki Celik", "FB", "Roma", "starter"),
        ("Ferdi Kadioglu", "FB", "Brighton", "starter"),
        ("Hakan Calhanoglu", "DM", "Inter", "star"),
        ("Orkun Kokcu", "CM", "Benfica", "starter"),
        ("Arda Guler", "AM", "Real Madrid", "star"),
        ("Kenan Yildiz", "W", "Juventus", "star"),
        ("Kerem Akturkoglu", "W", "Fenerbahce", "starter"),
        ("Baris Alper Yilmaz", "ST", "Galatasaray", "starter"),
        ("Semih Kilicsoy", "ST", "Besiktas", "squad"),
    ],
    "Ivory Coast": [
        ("Yahia Fofana", "GK", "Angers", "starter"),
        ("Odilon Kossounou", "CB", "Atalanta", "starter"),
        ("Evan Ndicka", "CB", "Roma", "starter"),
        ("Ousmane Diomande", "CB", "Sporting", "starter"),
        ("Ghislain Konan", "FB", "Sivasspor", "squad"),
        ("Franck Kessie", "CM", "Al-Ahli", "star"),
        ("Seko Fofana", "CM", "Rennes", "starter"),
        ("Simon Adingra", "W", "Brighton", "starter"),
        ("Nicolas Pepe", "W", "Villarreal", "starter"),
        ("Sebastien Haller", "ST", "Utrecht", "starter"),
        ("Amad Diallo", "W", "Manchester United", "star"),
        ("Jean-Philippe Krasso", "ST", "Red Star Belgrade", "squad"),
    ],
    "Algeria": [
        ("Alexandre Oukidja", "GK", "Metz", "starter"),
        ("Aissa Mandi", "CB", "Lille", "starter"),
        ("Ramy Bensebaini", "FB", "Borussia Dortmund", "starter"),
        ("Youcef Atal", "FB", "Al-Sadd", "squad"),
        ("Nabil Bentaleb", "DM", "Lille", "starter"),
        ("Ismael Bennacer", "CM", "AC Milan", "star"),
        ("Houssem Aouar", "AM", "Roma", "starter"),
        ("Riyad Mahrez", "W", "Al-Ahli", "star"),
        ("Said Benrahma", "W", "Lyon", "starter"),
        ("Amine Gouiri", "ST", "Marseille", "starter"),
        ("Baghdad Bounedjah", "ST", "Al-Sadd", "starter"),
        ("Yacine Brahimi", "AM", "Al-Gharafa", "squad"),
    ],
}
